### ISSUE TITLE
Updating a result doesn't work right.

### ISSUE THREAD

**Issue by dbtmurray** [irishchessunion/icu_ratings_app#13]
Raises a failure like this
```
{
  :controller=>"Admin::ResultsController",
  :action=>"update",
  :params=>{"utf8"=>"✓", "_method"=>"patch", "result"=>{"round"=>"6", "player_id"=>"79818", "opponent_id"=>"79797", "result"=>"D", "rateable"=>"true", "colour"=>"W"}, "controller"=>"admin/results", "action"=>"update", "id"=>"286592"},
  :format=>:js,
  :method=>"POST",
  :path=>"/admin/results/286592",
  :exception=>["ArgumentError", "wrong number of arguments (given 1, expected 0)"]
}
```

workaround is to update the result, then update the opponent's result. Both will raise this failure but it seems to work.

**Comment by ninkibah** [comment]
From the logs:
```
I, [2025-09-18T11:51:52.125776 #2500486]  INFO -- : Started PATCH "/admin/results/433821" for 109.78.49.141 at 2025-09-18 11:51:52 +0000
I, [2025-09-18T11:51:52.126838 #2500486]  INFO -- : Processing by Admin::ResultsController#update as JS
I, [2025-09-18T11:51:52.126885 #2500486]  INFO -- :   Parameters: {"utf8"=>"✓", "result"=>{"round"=>"1", "player_id"=>"146731", "opponent_id"=>"146774", "result"=>"L", "rateable"=>"true", "colour"=>"B"}, "id"=>"433821"}
I, [2025-09-18T11:51:52.147472 #2500486]  INFO -- : Completed 500 Internal Server Error in 21ms (Allocations: 6295)
F, [2025-09-18T11:51:52.147837 #2500486] FATAL -- :
ArgumentError (wrong number of arguments (given 1, expected 0)):

app/models/result.rb:75:in `update_results'
app/controllers/admin/results_controller.rb:29:in `update'
config/initializers/monkey.rb:24:in `block in process_action'
config/initializers/monkey.rb:23:in `process_action'

```

**Comment by ninkibah** [comment]
I think the fix is just to change line 75 of result.rb:
```
   new_opponent = opponent
```
